### ISSUE TITLE
Add `grpcio-tools` to requirements.txt

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/httpstan#17]
Or is this package only needed if one compiles from source (protos).

**Comment by ariddell** [comment]
It's neither. It's a build requirement. For a long time there was no such thing in Python because wheels were not popular. Now you have to distinguish between requirements (i.e., those to use the library), test requirements (to run the tests) and build requirements (to build the wheel).

I'm not sure what the conventions are about how to deal with this. I'm not sure they really exist yet. There's [PEP518](https://www.python.org/dev/peps/pep-0518/) which was recently adopted by ``pip`` but I'm not sure how helpful this will be.

The distinction is important too. We really don't want to signal to users that they need to install grpcio-tools (~20M) since it isn't a requirement to use httpstan.

Adding a note about this to the README would be a good idea.
