### ISSUE TITLE
STAN_THREADS does not use available cores

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#430]
We can, apparently, set STAN_THREADS to -1 to have Stan use as many threads as there are available cores.

See https://github.com/stan-dev/math/blob/c9228d7b513a609e7f6c40d52f9112090dec66cf/doxygen/parallelism_support/threading_tbb.md

@wds15 This is correct, right?

**Comment by wds15** [comment]
You need  to define STAN_THREADS during compilation and set STAN_NUM_THREADS to -1, then Stan will use all physical cores.

**Comment by ahartikainen** [comment]
STAN_THREADS is on by default.

Will there be a day when we can define STAN_NUM_THREADS and TBB shares that amount of cores automatically between different chains / processes?

Or do we need a Threading based chains for it?

**Comment by wds15** [comment]
You can do that already now if you want to. I would create a task arena with the desired concurrency and then you use the pattern as here:

https://software.intel.com/en-us/node/506359

 to run things in the background.

Ideally this pattern lands in stan services at some point.

**Comment by riddell-stan** [comment]
@wds15 Could we have STAN_NUM_THREADS set by default to -1? This seems like a more sensible default in the era of multicore computers.

**Comment by wds15** [comment]
Better would be to set the number of threads via the services, but that’s a bigger task to tackle I think. Setting the default to use all cores does not make sense as we usually run multiple chains and In that case you do not want to run more threads than physical cores.

**Comment by riddell-stan** [comment]
@wds15 Are you certain that it would be slower? One reason I think it would be faster: with 4 or 8 long-running chains it's very often the case that one chain will finish (long) before the other chains. So a core is idle for some time during the end of the run.

**Comment by ahartikainen** [comment]
Also, why would TBB split processing evenly if resources are not available?

**Comment by wds15** [comment]
@riddell-stan Oversubscription is good if chains do indeed finish very differently. Then longer running chains can take advantage of freed resources. However, that's very problem specific and I thought that Stan got a lot better in this regard so that we get more consistent inference times.

@ahartikainen You are right in that the TBB will actually avoid over-subscription if things work out. So maybe you just try it. What makes me worrying here is that there are different processes running, but possibly things work magically since the Stan programs are dynamically linked to the same library and as such making it possible to have a centrally managed resource pool (I really don't know, so please let me know what you find). The problem which remains is hyper-threading which usually slows things down, since Stan programs pump up CPU caches.

**Comment by riddell-stan** [comment]
@wds15 STAN_NUM_THREADS=1 seems like it's obviously the wrong default in a multicore world. Many other values would be better. `STAN_NUM_THREADS=min(1, cpu_count // 2)`, for example.

**Comment by wds15** [comment]
Feel free to file an issue for Stan math. The main problem is that we run multiple chains at the same time and then using all cpu s for just one chain is not ideal as it massively over subscribes.
