### ISSUE TITLE
httpstan does not build on Windows

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan#55]
See PR #54 for a mostly-working appveyor config.

I've lost track of all the fixes needed to get PyStan building on Windows. In principle, httpstan should be able to use the same fixes.

**Comment by ahartikainen** [comment]
TBH I don't believe MSVC++ will be able to compile Stan anytime soon. (It might be that some future update will bring the fixes we will need).

What we could try to do is to switch to `clan-cl` interface. Based on some googling other have had more success with it.

Third option is to use gcc compiler (mingw-w64).

**Comment by bob-carpenter** [comment]
gcc is probably most likely to work with the MPI and GPU support coming in 2.18 and 2.19, and it's what comes with the Windows toolchain.  So there are some pluses to standardizing on that across interfaces as a default on Windows if possible.

**Comment by ahartikainen** [comment]
`uvloop` is not currently supported on Windows.

I think we could meet the following specs to support Windows users

- use json (until uvloop works). Was it so that `json` was slow? Maybe with some clever chunking this could be done faster, because it is the slow part is to call the function multiple times?
- `-DSTAN_THREADS` not in by default (for Windows users). The `thread_local` is the problem, not normal threading.

**Comment by riddell-stan** [comment]
We can selectively disable uvloop on Windows (and just use stock asyncio).

As for threading, I think we do need to use `-DSTAN_THREADS` if we want to do parallel sampling using threads because the automatic differentiation implementation requires it. There may be a way to do parallel sampling using `multiprocessing` but I suspect it will not be nearly as simple as the current implementation.

**Comment by riddell-stan** [comment]
httpstan now builds on Windows.
