### ISSUE TITLE
Source release of httpstan on pypi

### ISSUE THREAD

**Issue by tillahoffmann** [stan-dev/httpstan#583]
Would it be possible to publish a source release on pypi for httpstan? I'm currently using an Apple M1 processor for which wheels do not yet exist, but building from source works fine. However, it would be nice to not have to install httpstan manually in every virtual environment but instead have it build from source via `pip install`.

**Comment by tillahoffmann** [comment]
Alright, I've now got a version of httpstan that is pip-installable by running the `make` step as part of the standard build process. Diff is [here](https://github.com/stan-dev/httpstan/compare/main...tillahoffmann:pip?expand=1).

**Comment by riddell-stan** [comment]
Thanks for looking into this. Maybe post a link to your version on the forums so other ARM users can pip install it?

Minor notes:
- Users need to have make and curl installed, in addition to a compiler.
- I don't think python-pybind11 is required. The relevant version is fetched when `make` is run.

As for incorporating this, I think we should probably go the route described by scikit-build, since it handles everything elegantly. In particular, it will work even if the user doesn't have curl or make installed.
